spring:
  application:
    name: 烧烤云
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://47.104.98.3:3306/test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ss1249517881

server:
  port: 443    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。
  ssl:
    key-store-password: e6XuN9sd    #填写pfx-password.txt文件内的密码。
    key-store-type: PKCS12
    key-store: classpath:7618213_xjsmile.pfx   #您需要使用实际的证书名称替换domain name.pfx。

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

